/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.interna;

import javax.accessibility.AccessibleContext;
import javax.swing.Icon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JRootPane;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.EventListenerList;
import javax.swing.plaf.ComponentUI;

/**
 *
 * @author 59399
 */
public class ViewUsuarios extends javax.swing.JInternalFrame {

    public ViewUsuarios() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        jComboPersonas = new javax.swing.JComboBox<>();
        txtClave = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jTextField11 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCriterio = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnBuscar = new javax.swing.JButton();
        jCheckMostrar = new javax.swing.JCheckBox();
        btnLimpCriterio = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        btnReporteGeneral = new javax.swing.JButton();
        btnReporteIndividual = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableUsuario = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setResizable(true);
        setTitle("Usuarios");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Administración de Usuarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 15))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Persona");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Usuario");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Clave");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 340, 10));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 340, -1));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 340, 20));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/icon-save.png"))); // NOI18N
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/icon-actualizar.png"))); // NOI18N
        jPanel2.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/icon-delete.png"))); // NOI18N
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, -1));

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/icon-clear.png"))); // NOI18N
        jPanel2.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsuario.setBorder(null);
        jPanel2.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 340, -1));

        jComboPersonas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 340, -1));
        jPanel2.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 340, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 404, 511));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Búsqueda de usuarios", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 15))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones de Búsqueda", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 15))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField11.setBorder(null);
        jPanel5.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 340, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Criterio:");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtCriterio.setToolTipText("Nombres:");
        txtCriterio.setBorder(null);
        jPanel5.add(txtCriterio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 310, 30));
        jPanel5.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 310, 10));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/sear.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        jPanel5.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, 40));

        jCheckMostrar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jCheckMostrar.setText("Mostrar Todos");
        jPanel5.add(jCheckMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, -1, -1));

        btnLimpCriterio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/icon-clear.png"))); // NOI18N
        jPanel5.add(btnLimpCriterio, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 770, 120));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Usuarios", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 15))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/cross.gif"))); // NOI18N
        jButton6.setText("Cancelar");
        jPanel6.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, -1, 40));

        btnReporteGeneral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/icon-printer.png"))); // NOI18N
        jPanel6.add(btnReporteGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, -1, -1));

        btnReporteIndividual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/printed.png"))); // NOI18N
        jPanel6.add(btnReporteIndividual, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, -1));

        jScrollPane1.setViewportView(jtableUsuario);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 740, 250));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 770, 350));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 780, 511));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpCriterio;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnReporteGeneral;
    private javax.swing.JButton btnReporteIndividual;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckMostrar;
    private javax.swing.JComboBox<String> jComboPersonas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTable jtableUsuario;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtCriterio;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    public JTable getJtableUsuario() {
        return jtableUsuario;
    }

    public void setJtableUsuario(JTable jtableUsuario) {
        this.jtableUsuario = jtableUsuario;
    }

    public void setBtnBuscar(JButton btnBuscar) {
        this.btnBuscar = btnBuscar;
    }

    public JButton getBtnEditar() {
        return btnEditar;
    }

    public void setBtnEditar(JButton btnEditar) {
        this.btnEditar = btnEditar;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public void setBtnEliminar(JButton btnEliminar) {
        this.btnEliminar = btnEliminar;
    }

    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    public void setBtnGuardar(JButton btnGuardar) {
        this.btnGuardar = btnGuardar;
    }

    public JButton getBtnLimpCriterio() {
        return btnLimpCriterio;
    }

    public void setBtnLimpCriterio(JButton btnLimpCriterio) {
        this.btnLimpCriterio = btnLimpCriterio;
    }

    public JButton getBtnLimpiar() {
        return btnLimpiar;
    }

    public void setBtnLimpiar(JButton btnLimpiar) {
        this.btnLimpiar = btnLimpiar;
    }

    public JButton getBtnReporteGeneral() {
        return btnReporteGeneral;
    }

    public void setBtnReporteGeneral(JButton btnReporteGeneral) {
        this.btnReporteGeneral = btnReporteGeneral;
    }

    public JButton getBtnReporteIndividual() {
        return btnReporteIndividual;
    }

    public void setBtnReporteIndividual(JButton btnReporteIndividual) {
        this.btnReporteIndividual = btnReporteIndividual;
    }

    public JCheckBox getjCheckMostrar() {
        return jCheckMostrar;
    }

    public void setjCheckMostrar(JCheckBox jCheckMostrar) {
        this.jCheckMostrar = jCheckMostrar;
    }

    public JComboBox<String> getjComboPersonas() {
        return jComboPersonas;
    }

    public void setjComboPersonas(JComboBox<String> jComboPersonas) {
        this.jComboPersonas = jComboPersonas;
    }

    public JPasswordField getTxtClave() {
        return txtClave;
    }

    public void setTxtClave(JPasswordField txtClave) {
        this.txtClave = txtClave;
    }


    public JTextField getTxtCriterio() {
        return txtCriterio;
    }

    public void setTxtCriterio(JTextField txtCriterio) {
        this.txtCriterio = txtCriterio;
    }

    public JTextField getTxtUsuario() {
        return txtUsuario;
    }

    public void setTxtUsuario(JTextField txtUsuario) {
        this.txtUsuario = txtUsuario;
    }
   
 
}
