/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JSeparator;

/**
 *
 * @author 59399
 */
public class ViewAdministration extends javax.swing.JFrame {

    /**
     * Creates new form ViewAdministration
     */
    public ViewAdministration() {
        initComponents();
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public JMenu getjMenu2() {
        return jMenu2;
    }

    public void setjMenu2(JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JSeparator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JMenuItem getMenuPersona() {
        return menuPersona;
    }

    public void setMenuPersona(JMenuItem menuPersona) {
        this.menuPersona = menuPersona;
    }

    public JMenuItem getMenuProductos() {
        return menuProductos;
    }

    public void setMenuProductos(JMenuItem menuProductos) {
        this.menuProductos = menuProductos;
    }

    public JMenuItem getMenuUsuario() {
        return menuUsuario;
    }

    public void setMenuUsuario(JMenuItem menuUsuario) {
        this.menuUsuario = menuUsuario;
    }

    public JDesktopPane getPanelEscritorio() {
        return panelEscritorio;
    }

    public void setPanelEscritorio(JDesktopPane panelEscritorio) {
        this.panelEscritorio = panelEscritorio;
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEscritorio = new javax.swing.JDesktopPane();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuPersona = new javax.swing.JMenuItem();
        menuUsuario = new javax.swing.JMenuItem();
        menuProductos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelEscritorio.setBackground(new java.awt.Color(0, 51, 102));

        panelEscritorio.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelEscritorioLayout = new javax.swing.GroupLayout(panelEscritorio);
        panelEscritorio.setLayout(panelEscritorioLayout);
        panelEscritorioLayout.setHorizontalGroup(
            panelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEscritorioLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(358, 358, 358))
        );
        panelEscritorioLayout.setVerticalGroup(
            panelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEscritorioLayout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 51, 102));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/btnconfig.png"))); // NOI18N

        menuPersona.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        menuPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/icon_cliente.png"))); // NOI18N
        menuPersona.setText("Personas");
        menuPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPersonaActionPerformed(evt);
            }
        });
        jMenu1.add(menuPersona);

        menuUsuario.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        menuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/icon-usuario.png"))); // NOI18N
        menuUsuario.setText("Usuario");
        jMenu1.add(menuUsuario);

        menuProductos.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        menuProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/boxes.png"))); // NOI18N
        menuProductos.setText("Productos");
        jMenu1.add(menuProductos);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/btnReportes.png"))); // NOI18N
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuPersonaActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem menuPersona;
    private javax.swing.JMenuItem menuProductos;
    private javax.swing.JMenuItem menuUsuario;
    private javax.swing.JDesktopPane panelEscritorio;
    // End of variables declaration//GEN-END:variables
}
